# hold-out

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
df = sns.load_dataset('tips')

In [2]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
y_col = 'tip'
X = df.drop(columns=[y_col])
numeric_cols = X.select_dtypes(include=np.number)

In [4]:
numeric_cols

     total_bill  size
0         16.99     2
1         10.34     3
2         21.01     3
3         23.68     2
4         24.59     4
..          ...   ...
239       29.03     3
240       27.18     2
241       22.67     2
242       17.82     2
243       18.78     2

[244 rows x 2 columns]

In [5]:
X.dtypes

total_bill     float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [6]:
category_cols = X.select_dtypes(include='category')

In [7]:
category_cols

        sex smoker   day    time
0    Female     No   Sun  Dinner
1      Male     No   Sun  Dinner
2      Male     No   Sun  Dinner
3      Male     No   Sun  Dinner
4    Female     No   Sun  Dinner
..      ...    ...   ...     ...
239    Male     No   Sat  Dinner
240  Female    Yes   Sat  Dinner
241    Male    Yes   Sat  Dinner
242    Male     No   Sat  Dinner
243  Female     No  Thur  Dinner

[244 rows x 4 columns]

In [8]:
numeric_cols = X.select_dtypes(include=np.number).columns.to_list()

In [9]:
numeric_cols

['total_bill', 'size']

In [10]:
X = pd.get_dummies(X, drop_first=True)

In [11]:
X.dtypes

total_bill     float64
size             int64
sex_Female        bool
smoker_No         bool
day_Fri           bool
day_Sat           bool
day_Sun           bool
time_Dinner       bool
dtype: object

In [12]:
y = df[y_col]

In [13]:
y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [14]:
X

,total_bill,size,sex_Female,smoker_No,day_Fri,day_Sat,day_Sun,time_Dinner
0,16.99,2,True,True,False,False,True,True
1,10.34,3,False,True,False,False,True,True
2,21.01,3,False,True,False,False,True,True
3,23.68,2,False,True,False,False,True,True
4,24.59,4,True,True,False,False,True,True
...,...,...,...,...,...,...,...,...
239,29.03,3,False,True,False,True,False,True
240,27.18,2,True,False,False,True,False,True
241,22.67,2,False,False,False,True,False,True
242,17.82,2,False,True,False,True,False,True
243,18.78,2,True,True,False,False,False,True

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [16]:
print(len(X_train))
print(len(X_test))

170
74

In [17]:
# 標準化　（データ分割の後に実施）
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train[numeric_cols])

StandardScaler()

In [18]:
X_train_scaled = X_train.copy()
# 数値カラムのみ標準化
X_train_scaled[numeric_cols] = scaler.transform(X_train[numeric_cols])

In [19]:
X_train_scaled

,total_bill,size,sex_Female,smoker_No,day_Fri,day_Sat,day_Sun,time_Dinner
61,-0.682321,-0.616436,False,False,False,True,False,True
146,-0.152575,0.463915,True,True,False,False,False,False
52,1.620922,1.544266,True,True,False,False,True,True
66,-0.392771,-0.616436,True,True,False,True,False,True
26,-0.730580,-0.616436,False,True,False,True,False,True
...,...,...,...,...,...,...,...,...
67,-1.860266,-1.696786,True,False,False,True,False,True
192,0.922272,-0.616436,False,False,False,False,False,False
117,-1.028905,-0.616436,True,True,False,False,False,False
47,1.356598,1.544266,False,True,False,False,True,True
172,-1.401811,-0.616436,False,False,False,False,True,True

In [20]:
X_test_scaled = X_test.copy()
X_test_scaled[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [21]:
X_test_scaled

,total_bill,size,sex_Female,smoker_No,day_Fri,day_Sat,day_Sun,time_Dinner
64,-0.267738,0.463915,False,True,False,True,False,True
63,-0.190963,1.544266,False,False,False,True,False,True
55,-0.059349,-0.616436,False,True,False,False,True,True
111,-1.401811,-1.696786,True,True,False,True,False,True
225,-0.412513,-0.616436,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...
90,0.980401,-0.616436,False,False,True,False,False,True
101,-0.510127,-0.616436,True,False,True,False,False,True
75,-1.044260,-0.616436,False,True,False,True,False,True
4,0.500010,1.544266,True,True,False,False,True,True
109,-0.627482,-0.616436,True,False,False,True,False,True

In [22]:
X_test_scaled.mean()

total_bill    -0.088666
size          -0.003263
sex_Female     0.445946
smoker_No      0.527027
day_Fri        0.135135
day_Sat        0.351351
day_Sun        0.324324
time_Dinner    0.756757
dtype: float64

In [23]:
X_train_scaled.mean()

total_bill    -1.044916e-16
size          -1.671865e-16
sex_Female     3.176471e-01
smoker_No      6.588235e-01
day_Fri        5.294118e-02
day_Sat        3.588235e-01
day_Sun        3.058824e-01
time_Dinner    7.058824e-01
dtype: float64

In [24]:
# 線形回帰モデル学習
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_scaled, y_train)

LinearRegression()

In [25]:
y_pred = model.predict(X_test_scaled)

In [28]:
# モデルの評価（MSE）
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred) #np.mean(np.square(y_test - y_pred))

0.955080898861715

In [29]:
y_test

64     2.64
63     3.76
55     3.51
111    1.00
225    2.50
       ...
90     3.00
101    3.00
75     1.25
4      3.61
109    4.00
Name: tip, Length: 74, dtype: float64

## LOOCV

In [30]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [31]:
X = df['total_bill'].values.reshape(-1, 1)
y = df['tip']

In [33]:
X.shape

(244, 1)

In [41]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import LeaveOneOut
loo = LeaveOneOut()

In [42]:
model = LinearRegression()
mse_list = []
for train_index, test_index in loo.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # モデル学習
    model.fit(X_train, y_train)
    # テストデータの予測
    y_pred = model.predict(X_test)
    # MSE
    mse = mean_squared_error(y_test, y_pred)
    mse_list.append(mse)

In [46]:
print(f"MSE(LOOCV):{np.mean(mse_list)}")
print(f"std:{np.std(mse_list)}")

MSE(LOOCV):1.0675673489857438
std:2.0997944551776313

In [50]:
from sklearn.model_selection import cross_val_score
cv = LeaveOneOut()
scores = cross_val_score(model, X, y, cv=cv, scoring='neg_mean_squared_error')
print(f"MSE(LOOCV):{-np.mean(scores)}")
print(f"std:{np.std(scores)}")

MSE(LOOCV):1.0675673489857438
std:2.0997944551776313

## k-Fold CV

In [52]:
from sklearn.model_selection import KFold
k = 5
cv = KFold(n_splits=k, shuffle=True, random_state=0)
model = LinearRegression()
mse_list = []
for train_index, test_index in cv.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    # モデル学習
    model.fit(X_train, y_train)
    # テストデータ予測
    y_pred = model.predict(X_test)
    # MSE
    mse = mean_squared_error(y_test, y_pred)
    mse_list.append(mse)

In [53]:
mse_list

[0.8213090642766283,
 1.0745842125927971,
 1.0880123892600384,
 1.33238677149302,
 1.084763004349474]

In [58]:
print(f"MSE({k}FoldCV): {np.mean(mse_list)}")
print(f"std:{np.std(mse_list)}")

MSE(5FoldCV): 1.0802110883943916
std:0.16170100507039514

In [59]:
scores = cross_val_score(model, X, y, cv=cv, scoring='neg_mean_squared_error', n_jobs=-1)

In [60]:
scores

array([-0.82130906, -1.07458421, -1.08801239, -1.33238677, -1.084763  ])

In [61]:
mse_list

[0.8213090642766283,
 1.0745842125927971,
 1.0880123892600384,
 1.33238677149302,
 1.084763004349474]

In [62]:
print(f"MSE({k}FoldCV): {-np.mean(scores)}")
print(f"std:{np.std(scores)}")

MSE(5FoldCV): 1.0802110883943916
std:0.16170100507039514

In [73]:
# repeatedKFold
from sklearn.model_selection import cross_val_score, KFold, RepeatedKFold, train_test_split
import numpy as np
import pandas as pd
import seaborn as sns
df = sns.load_dataset('tips')
y_col = 'tip'
X = df['total_bill'].values.reshape(-1, 1)
X = df.drop(columns=[y_col])
# 標準化のために数値カラムのリストを取得
numeric_cols = X.select_dtypes(include=np.number).columns.to_list()
X = pd.get_dummies(X, drop_first=True)
y = df[y_col]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# 標準化
# 標準化は，データ分割の後に実施する
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = X_train.copy()
# 数値カラムのみ標準化
X_train_scaled[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test_scaled = X_test.copy()
X_test_scaled[numeric_cols] = scaler.transform(X_test[numeric_cols])

k = 5
n_repeats=3
cv = RepeatedKFold(n_splits=k, n_repeats=n_repeats, random_state=0)
model = LinearRegression()
mse_list = []
for train_index, test_index in cv.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    # モデル学習
    model.fit(X_train, y_train)
    # テストデータ予測
    y_pred = model.predict(X_test)
    # MSE
    mse = mean_squared_error(y_test, y_pred)
    mse_list.append(mse)

In [74]:
mse_list

[0.893919522160949,
 1.1013322339228646,
 1.4131374807731674,
 1.3445333382295759,
 1.090175715119653,
 1.1490203135873551,
 1.5884575078386274,
 1.0842603203118317,
 0.7980892602322375,
 0.9157310178481186,
 0.9284503100701684,
 1.737256790407572,
 0.7252284152154943,
 1.1565776342528895,
 1.1962083904962972]

In [76]:
scores = cross_val_score(model, X, y, cv=cv, scoring='neg_mean_squared_error', n_jobs=-1)

In [77]:
scores

array([-0.89391952, -1.10133223, -1.41313748, -1.34453334, -1.09017572,
       -1.14902031, -1.58845751, -1.08426032, -0.79808926, -0.91573102,
       -0.92845031, -1.73725679, -0.72522842, -1.15657763, -1.19620839])

# Pipeline

## Pipeline + KFold

In [85]:
from sklearn.pipeline import Pipeline
pipeline = Pipeline(steps=[('scaler', StandardScaler()), ('model', LinearRegression())])
cv = KFold(n_splits=5, shuffle=True, random_state=0)
scores = cross_val_score(pipeline, X, y, scoring='neg_mean_squared_error', cv=cv)
scores

array([-0.89391952, -1.10133223, -1.41313748, -1.34453334, -1.09017572])

In [90]:
## Pipelineなし
# 標準化＋線形回帰
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
model =LinearRegression()
scaler = StandardScaler()
X_train_scaled  = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

In [91]:
y_pred

array([2.82249035, 2.97504474, 2.8260184 , 1.38113692, 3.15154584,
       1.72121268, 2.48332645, 3.03579004, 2.75176346, 4.52560955,
       3.1133346 , 3.14781575, 2.33198109, 2.11518372, 2.93262778,
       4.27846609, 1.83157994, 2.26626275, 2.31085596, 3.24382161,
       3.81889336, 2.85616455, 2.42949782, 2.42039736, 2.20253234,
       2.42509643, 2.81777778, 4.70274951, 3.81268552, 2.38673795,
       2.29194112, 2.20803273, 2.45503466, 1.7743294 , 2.71663745,
       2.22913684, 2.72146912, 2.01205852, 5.85346207, 3.49435578,
       2.26246168, 2.20347519, 2.50905642, 4.41646769, 1.97212663,
       2.78445294, 2.65274212, 3.01652357, 2.73423023, 3.95761528,
       3.9498931 , 2.53992971, 2.71758399, 6.35620823, 1.7434279 ,
       2.33450139, 4.23562521, 3.29319236, 2.41114285, 2.20345847,
       3.72455103, 2.29099827, 3.04008335, 3.74539008, 4.01431996,
       2.26547605, 2.66047323, 3.84238482, 2.17921165, 3.87859588,
       2.59899485, 1.94814647, 3.70801825, 2.11341037])

In [92]:
y_test

64     2.64
63     3.76
55     3.51
111    1.00
225    2.50
       ...
90     3.00
101    3.00
75     1.25
4      3.61
109    4.00
Name: tip, Length: 74, dtype: float64

In [95]:
## Pipelineあり
# 標準化＋線形回帰
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
pipeline = Pipeline(steps=[('scaler', StandardScaler()), ('model', LinearRegression())])
pipeline.fit(X_train, y_train)
y_pred_p = pipeline.predict(X_test)

In [96]:
y_pred_p

array([2.82249035, 2.97504474, 2.8260184 , 1.38113692, 3.15154584,
       1.72121268, 2.48332645, 3.03579004, 2.75176346, 4.52560955,
       3.1133346 , 3.14781575, 2.33198109, 2.11518372, 2.93262778,
       4.27846609, 1.83157994, 2.26626275, 2.31085596, 3.24382161,
       3.81889336, 2.85616455, 2.42949782, 2.42039736, 2.20253234,
       2.42509643, 2.81777778, 4.70274951, 3.81268552, 2.38673795,
       2.29194112, 2.20803273, 2.45503466, 1.7743294 , 2.71663745,
       2.22913684, 2.72146912, 2.01205852, 5.85346207, 3.49435578,
       2.26246168, 2.20347519, 2.50905642, 4.41646769, 1.97212663,
       2.78445294, 2.65274212, 3.01652357, 2.73423023, 3.95761528,
       3.9498931 , 2.53992971, 2.71758399, 6.35620823, 1.7434279 ,
       2.33450139, 4.23562521, 3.29319236, 2.41114285, 2.20345847,
       3.72455103, 2.29099827, 3.04008335, 3.74539008, 4.01431996,
       2.26547605, 2.66047323, 3.84238482, 2.17921165, 3.87859588,
       2.59899485, 1.94814647, 3.70801825, 2.11341037])